Fix StringIO/BytesIO stuck issue
We all know the way python3 handles strings is a bit different.

$ python2
Python 2.7.16 (default, Apr 30 2019, 15:54:43)
[GCC 9.0.1 20190312 (Red Hat 9.0.1-0.10)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import io
>>> s=io.BytesIO()
>>> s.write('hello')
5L
>>> s.getvalue()
'hello'
>>> s=io.StringIO()
>>> s.write('hello')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unicode argument expected, got 'str'
>>> s.write(u'hello')
5L
>>> s.getvalue()
u'hello'
>>>

$ python3
Python 3.6.8 (default, Dec  5 2019, 15:45:45)
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import io
>>> s=io.BytesIO()
>>> s.write('hello')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: a bytes-like object is required, not 'str'
>>> s.write(b'hello')
5
>>> s.getvalue()
b'hello'
>>> s=io.StringIO()
>>> s.write('hello')
5
>>> s.getvalue()
'hello'
>>>

The way Python2 and Python3 handles String and Bytes IO is different.
* In Python2 BytesIO() accepts text format syntax, and StringIO() expects unicodes
* While in Python3 StringIO() accepts text format syntax, and BytesIO() expects bytes like objects

I think the compatibility of using both the IO streams with python2 and python3 is compromised.

Hence this patch, uses BytesIO() and StringIO() based on python version.

Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>